### ISSUE TITLE
Error warning when installing

### ISSUE THREAD

**Issue by JohanFalt** [justinross/foundry-bitd-alternate-sheets#58]
Take the manifest json -> https://github.com/justinross/foundry-bitd-alternate-sheets/releases/latest/download/module.json
(also can't be found by Foundry VTT version problem? I use v10).

When forcing install with manifest I get the following error:

![image](https://user-images.githubusercontent.com/57871596/216619167-b68759f3-4cc9-4ea0-aa59-63f71a166c08.png)

**Comment by justinross** [comment]
I’m not able to reprodue this issue. I’ve experienced this once or twice myself, but it’s always been a Foundry issue. Refreshing the foundry page or restarting Foundry tends to resolve it for me. Give that a try?

Also, I’d suggest installing from the Foundry module registry, rather than by manifest.

**Comment by JohanFalt** [comment]
Got it to work. A missunderstanding on my part - I thought this was a system, but now as I READ the texts I understood that it was a module. Installed the system added your module and tested.

Everything worked perfectly. Thank you :)

**Comment by justinross** [comment]
Hooray!
