### ISSUE TITLE
Playbook change issue

### ISSUE THREAD

**Issue by drewg13** [justinross/foundry-bitd-alternate-sheets#6]
This one is harder to track down, but I can consistently reproduce it:

1.  Create new Actor
2.  Drop 'Ghost' class item on it
3.  Note attributes change, but nothing else
4.  Refresh/reopen sheet
5.  Note correct abilities/items/friends now

Hmm, this also appears to occur when changing playbooks by dropping a new class.  The attributes and friends update, but the abilities and items get wiped until a refresh/reopen.  I suspect some race condition in the getData() perhaps.

**Comment by justinross** [comment]
Yeah, I've noticed this one a few times and haven't been able to track it down.

Abilities and items are both virtual lists being generated in getData(), so you're probably right about the race condition. I'm guessing it's being caused by the sheet rerendering before the playbook item has actually been added via drag/drop. It seems like the rerenders from adding the NPCs should fix that though. 

I wonder if there's a way to ensure my drop handler runs after Foundry finishes its item drop stuff. 

(Also, the "weird" playbooks aren't really supported at the moment, but that's not what's causing this issue)

**Comment by justinross** [comment]
Fixed, I think.
