### ISSUE TITLE
Trauma list issues for newly created Actors

### ISSUE THREAD

**Issue by drewg13** [justinross/foundry-bitd-alternate-sheets#9]
This one is bizarre, but sometime after creating my 2nd test Actor or so, I noticed that all newly created Actors now display like this:
![image](https://user-images.githubusercontent.com/1455026/179035634-af086069-8b16-41c2-b784-16bd1494e160.png)

This persists across refreshes and total Foundry resets.  Digging into the code, it looks like those are all Foundry-defined methods added to `Array.prototype`.  This is the section of `getData()` where things are going wrong:
```js
for(const trauma in data.data.trauma.list){
      if(data.data.trauma.list[trauma]){
        trauma_array.push(trauma);
      }
    }
    data.trauma_array = trauma_array;
```
Because `data.data.trauma.list` is an empty array on these new Actors, that code is (for some unknown reason) grabbing the method names and shoving them into the array instead.

It appears that the array doesn't get populated until you click a Trauma on the old sheets, so switching sheets, clicking a Trauma, unclicking that Trauma, then switching back to the alt sheets, fixes the problem.  You're going to need to find a way to pre-populate that array somehow.  My method in my forks of base Blades was to do something like this in the Actor class:
```js
/** @override */
  async _preCreate( createData, options, userId ) {
    await super._preCreate( createData, options, userId );
    const updateData = {};

    if( createData.type === "character" ) {
      updateData['data.trauma.list'] = game.system.traumaList.reduce( ( key, val ) => ( key[val]=false, key ), {} );
    }

    await this.data.update( updateData );
  }
```
But that came about as a consequence of pulling the traumas out to facilitate translations and, as a module, you don't necessarily have control of the same things.  I've tried extending the Actor class, but I can't figure out how to take control of the default Actor class from a module, because setting `CONFIG.Actor.documentClass = BladesAlternateActor` is how I would do it from a system, but doesn't seem to work from a module.

Adding this code into the `getData()` just before the rest of the trauma handling code seems to fix the problem on a refresh/re-open, but I can't figure out why the `render` method isn't re-rendering the sheet, so it's still an unsatisfying solution:
```js
if( data.data.trauma.list.length === 0 ){
      let list = data.data.trauma.options.reduce( ( key, val ) => ( key[val]=false, key ), {} );
      await this.actor.update( { "data.trauma.list": list } );
      this.actor.sheet.render(true);
    }
```

Perhaps it would make more sense to validate `data.data.trauma.list` against `data.data.trauma.options` at this point in order to accommodate changes to that list.

**Comment by justinross** [comment]
I've run a similar issue before, but not for a long time. Like, back when this was a system update, not a module. 

It seems like it only happens to characters created while my sheet is the default character sheet. That'll help figure out a solution.

What I think is happening is that the trauma list gets prepopulated as an object with the default sheets (`{cold: false, haunted: false ...}` etc.), and my sheets don't do that. I *think* it's happening because the default sheets are displaying the traumas like this: 
![image](https://user-images.githubusercontent.com/1120106/179311816-9e59de16-58c2-460a-8519-f21937d5ca71.png)
and Foundry is binding those checkboxes to the data (and vice versa), so it's like "oh, this checkbox is named '`data.trauma.list.haunted`', and it's false, so I'll make `data.trauma.list` an object, then set its `haunted` property to false, even though nothing has changed". 

Whatever the cause, though, my getData() is assuming that data.trauma.list is an object of that sort, so I'm using `for ...  in`, to iterate over the object keys. `for ... in` is for iterating over objects/keys. I'm not sure why, but `for ... in` loops run on arrays will return prototype overrides: https://jsfiddle.net/z2x1mrdt/

I think I'll just need to account for both scenarios in my `getData()`. That way I don't have to mess with changing system data structures.
